### ISSUE TITLE
Infer siblings with only shared father

### ISSUE THREAD

**Issue by matthdsm** [brentp/somalier#104]
Hi Brent

I was wondering if it's possible to infer relatedness between 2 samples who might share the same father.
We have 2 donor children with very similar variants and we're wondering if those variants are inherited from the same donor, since the mothers don't share the genotypes.

Thanks
M

**Comment by brentp** [comment]
Hi Matthias, 
if they have same father and different mothers, they'd be related at 0.25 level, so you should simply be able to check the relatedness value (assuming it's high-quality, high-depth, dense genotypes). Somalier won't infer, but you could verify this also if the mothers appear to be unrelated.

**Comment by matthdsm** [comment]
Thanks! That's exactly what we got!
