### ISSUE TITLE
relatedness calculation

### ISSUE THREAD

**Issue by danielecook** [brentp/somalier#11]
The relatedness values you report are negative in some cases presumably because you provide an adjusted relatedness value. Is there more info on this somewhere or would it be possible to provide a little more context in terms of interpreting those values? Thanks - great tool!

**Comment by brentp** [comment]
hi, glad it's useful.
the relatedness calculation is described in peddy (https://www.ncbi.nlm.nih.gov/pubmed/28190455) it is expected that unrelated samples will have negative values--there's no reason to think it will converge to 0.

**Comment by danielecook** [comment]
Thank you for the clarification!
