### ISSUE TITLE
Sex QC for one sample

### ISSUE THREAD

**Issue by solcos** [brentp/somalier#116]
Hello! I am new to Somalier and I'm trying to perform a sex determination for one sample in a BAM file. 

I am getting the next plot for sex determination.
![image](https://github.com/brentp/somalier/assets/92781950/2eaf5e5a-cae6-415e-841d-024274a394da)

I am wondering if this is the expected result, compared to the one you provide in github "https://brentp.github.io/somalier/ex.html" it seems biased in some way. And also if there is a way to have a better result, if that is the case. Should it be a good approach to add 'control' samples in it? Or do you know a better approach to perform the sex determination QC?

Thanks in advance!

**Comment by solcos** [comment]
Hello! In case there is something sensitive, can I share it by email?

**Comment by brentp** [comment]
@solcos I never got the email.

**Comment by brentp** [comment]
Hi, I had a look at the file, this sample must be XX. There are plenty of hom-ref and hom-alt sites on the X chromosome.
You might want to check for large structural variants on X to account for the lower coverage or run a tool like indexcov if this is WGS. If it's exome, then it's not too suprising that the coverage is off.
Hope this helps,
-Brent

**Comment by solcos** [comment]
Thanks I will do that and take a look at them. Thanks!
