### ISSUE TITLE
Legend results in relatedness plot

### ISSUE THREAD

**Issue by solcos** [brentp/somalier#117]
Hello!

I am quite new to the field and Somalier. Maybe it is a very basic question but, I have doubts on how to interpret the legend of the relatedness plot of the 'somalier.html'. Regarding the image below, I undestand all the different groups except '0.250', can you explain what is referring to?

Thanks in advance!

![image](https://github.com/brentp/somalier/assets/92781950/3d50ffd6-bb2e-4f31-ab06-ab8608bdaec1)

**Comment by brentp** [comment]
Hi, you can read about the relatedness value here: https://en.wikipedia.org/wiki/Coefficient_of_relationship
note that relatedness is 2*kinship coefficient.
a value of 0.25 would be, for example grandparent to grand child or uncle to niece. The colors (and the coefficents they represent) are determined by the relationships in your pedigree file.

**Comment by solcos** [comment]
Thank you for your fast response! :)
