### ISSUE TITLE
[Question]: difference between sites.hg38.vcf.gz and sites.hg38.rna.vcf.gz

### ISSUE THREAD

**Issue by tamuanand** [brentp/somalier#118]
Hi @brentp 

I had a question on the difference between sites.hg38.vcf.gz and sites.hg38.rna.vcf.gz and when to use one or the other

- https://github.com/brentp/somalier/issues/75#issuecomment-852399046 
> are you using this sites file: https://github.com/brentp/somalier/files/4566475/sites.hg38.rna.vcf.gz
for RNA-seq? I should probably make that the default for WGS as well.
- https://github.com/brentp/somalier/issues/79#issuecomment-883937825
> You must run somalier extract with the same sites for all samples and assays. I recommned to use sites.hg38.rna.vcf.gz that will work well for WGS too.

Is `sites.hg38.rna.vcf.gz` supposed to be for RNASeq and WGS? Likewise is `sites.hg38.vcf.gz` supposed to be for WES? 

Thanks in advance.

**Comment by brentp** [comment]
Hi, if you have any samples with RNA, seq, I would use sites.hg38.rna.vcf.gz. Otherwise, use sites.hg38.vcf.gz (which will work for WES).
I expect both should give very similar results on WES/WGS, but the sites.hg38.rna.vcf.gz will likely have more usable sites on RNA-Seq.

**Comment by tamuanand** [comment]
Thanks @brentp
