### ISSUE TITLE
nan values break output .html

### ISSUE THREAD

**Issue by JosephMcCarter** [brentp/somalier#13]
One of the sample I used had low coverage (~0.5X) which caused a number of nan's in the html data, which broke it for a cohort of 500 samples.

`{"sample":"I-H-134715-T2-1-D1-1","gt_depth_mean":0.0,"gt_depth_std":nan,"gt_depth_skew":nan,"depth_mean":0.1543086172344688,"depth_std":0.5164978344309251,"depth_skew":4.036674201975204,"ab_mean":0.0,"ab_std":nan,"ab_skew":nan,"pct_other_alleles":27.21822541966425,"n_hom_ref":0,"n_het":0,"n_hom_alt":0,"n_unknown":998,"n_known":0},`

**Comment by brentp** [comment]
thanks for reporting. you can probably get around this for now by editing the html file to include:
```
var nan = NaN
```
just after the first `<script>` directive. But I will fix this properly for the next release.

**Comment by brentp** [comment]
I have just pushed a fix for this. The new release will be out today or tomorrow. Thanks again for reporting.

**Comment by JosephMcCarter** [comment]
Thank you!
