### ISSUE TITLE
sm1.somalier and no other output

### ISSUE THREAD

**Issue by methionine23** [brentp/somalier#130]
Hello, 
I tried somalier version: 0.2.19, which worked well on DNA data (thank you!). But when I run rnaseq data (with gtex/topmed reference, and sites.hg38.rna.vcf.gz), somalier extract didn't generate sample.somalier but a file named sm1.somalier in the folder. 

sm1.somalier looks binary and the beginning is:"
0209 4b47 4c37 3439 736d 3155 401a 0303
0001 0000 0042 0000 0002 0000 0000 0000
0001 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0005 0000 0000 0000
0000 0000 0003 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0056 0000
0000 0000 0002 0000 0000 0000 0000 0000
00fb 0000 00bf 0000 0001 0000 0001 0000
0000 0000 0000 0000 0011 0000 0011 0000
0000 0000 0000 0000 0000 0000 0000 0000
0006 0000 0000 0000 0000 0000 0000 0000
0002 0000 0000 0000 0000 0000 0000 0000

Any suggestions? Thanks again,

**Comment by brentp** [comment]
Hi, is your data in hg38 coordinates?
You can see the sites in the somalier VCF, so I'd check the depth in your bam/cram at a few of those sites.
What is the coverage?

**Comment by methionine23** [comment]
Bam and fast are in hg38. Coverage on the site.hg38.rna.vcf is like below:

**Comment by methionine23** [comment]
I tried to use the TOPmed fasta and grch38 with same sm1.somalier in the output folder.

**Comment by brentp** [comment]
well, your data is pretty sparse. I think somalier will save, but not use sites with less than 7 coverage. Also, the output file is named based on the read-group SM, so that must be `sm1`.
You can check with:
```
samtools view -H $bam | grep ^@RG
```

**Comment by methionine23** [comment]
I didn't realize the SM for these received bam (while using --sample-prefix=). All solved now, and thank you again!
