### ISSUE TITLE
Scaled mean depth on X - how to calculate?

### ISSUE THREAD

**Issue by parkjooyoung99** [brentp/somalier#132]
I am trying to reproduce the plot below with my somalier output. 
However, I could not find the exact method on how the axis are defined. 

Would there be someone who have solved this??
Thanks!
<img width="822" alt="image" src="https://github.com/brentp/somalier/assets/77565848/0e87b4cd-08ca-4ebf-9213-5f5918c179a2">

**Comment by brentp** [comment]
Hi, `somalier` uses this to get scaled mean depth on x:
```
2 * stats[i].x_dp.mean / stats[i].gtdp.mean
```
so it takes the mean depth on X and divides by the mean depth on the autosome for sites that met the depth cutoff. Then multiplies by 2 so we get e.g. ~2 for female and ~1 for male.
