### ISSUE TITLE
Missing groups.tsv

### ISSUE THREAD

**Issue by andreabc** [brentp/somalier#137]
Hello,

Would we expect an empty file or no file at all if there are no pairs of samples above the relatedness threshold?

I'm currently not seeing my "{output_prefix}.groups.tsv" file and wondering if this expected - I've managed to successfully run this (and get all expected output files) on all my other cohorts and this is the one exception

Many thanks

**Comment by brentp** [comment]
Hi, if no samples appear to be related above 0.125, then no groups file is created: https://github.com/brentp/somalier/blob/master/src/somalierpkg/relate.nim#L144

**Comment by andreabc** [comment]
great, thanks again!
