### ISSUE TITLE
Some grouped pairs in groups.csv shown as 'unrelated' in .html

### ISSUE THREAD

**Issue by JosephMcCarter** [brentp/somalier#14]
In a cohort of 500 samples, some samples pairs were marked as unrelated despite being grouped in the grouped.csv file.

for example

```
grep 133675 somalier_groups_impact_independant.csv
I-H-133675-T3-1-D1-1,I-H-133675-N2-1-D1-1,I-H-133675-T4-1-D1-1,I-H-133675-T5-1-D1-1,I-H-133675-T6-1-D1-1,I-H-133675-T7-1-D1-1,I-H-133675-T8-1-D1-1,I-H-133675-T9-1-D1-1,I-H-133675-T10-1-D1-1,I-H-133675-N2-2-D1-1
```

![Screen Shot 2019-03-27 at 4 44 34 PM](https://user-images.githubusercontent.com/25490440/55111330-878ad680-50b0-11e9-9940-93a09d197309.png)

**Comment by brentp** [comment]
can you share the html file?

**Comment by brentp** [comment]
or from the js console, can you show the output of:
```
input["expected-relatedness"]
```

**Comment by JosephMcCarter** [comment]
Here is the .html

[p230_somalier_run2_.somalier.html.zip](https://github.com/brentp/somalier/files/3015372/p230_somalier_run2_.somalier.html.zip)

**Comment by brentp** [comment]
great. thank you. I have fixed this. See attached (I just hand-edited your html and made same fix in somalier).
[fix.zip](https://github.com/brentp/somalier/files/3015395/fix.zip)

**Comment by brentp** [comment]
can you verify that HTML looks good to you? I have finished up some other dev and it's getting close to a new release for somalier. thanks again.

**Comment by JosephMcCarter** [comment]
Thank you!

**Comment by JosephMcCarter** [comment]
html for this specific issue looks good! - Thank you

however - I just noticed another in #15
