### ISSUE TITLE
Sites calculation

### ISSUE THREAD

**Issue by gcerchia** [brentp/somalier#141]
Hi!
I was testing the tool on a WGS trio and it's not clear to me how the sites considered for the calculations are counted. For example, in my case I have 3 individual VCF files and more than 10k sites extracted per sample, but in the output file (pairs.tsv) the sites are less (3k per sample pair). Can you explain to me all the filters applied to get the final number of sites used for relatedness calculation? Is it better to use a multi-sample VCF?

PS: In my case I don't have 0/0 variants from the original files and IBS0 is always 0, but it's strange because I'm not considering a WES or a small gene panel. I tried to use the "--unknown" option and the number of sites (and IBS0) has increased, but I'm not sure if it's the right solution

**Comment by brentp** [comment]
Hi, somalier works best on jointly called VCFs or bams, in your case, I would run `somalier extract` directly on the bams or crams.
On individual VCFs, there are, as you note, no 0/0 genotypes and there's no way to know if those are truly homozygous reference or if they are lacking coverage and therefore missing calls.
