### ISSUE TITLE
.html - toggling 'unrelated' data on/off makes portion of 'related' data invisible

### ISSUE THREAD

**Issue by JosephMcCarter** [brentp/somalier#15]
Toggling the 'unrelated' data by clicking the blue legend marker makes a portion of the 'related' data invisible;

![Screen Shot 2019-03-27 at 6 02 38 PM](https://user-images.githubusercontent.com/25490440/55115645-67ace000-50bb-11e9-9436-d1565ab09afa.png)

![Screen Shot 2019-03-27 at 6 02 48 PM](https://user-images.githubusercontent.com/25490440/55115664-72677500-50bb-11e9-808a-a9cbd89f7363.png)

**Comment by brentp** [comment]
hmm. I can see this. I'll see what I can do.

**Comment by brentp** [comment]
this seems to be a bug in plotly or the webgl lib upstream of plotly. I can get around it by changing:
```
        ix: x_data[i].ix,
        type: 'scattergl',
```
to:
```
        ix: x_data[i].ix,
        type: x_data[i].ix.length > 9999 ? 'scattergl' : 'scatter',
```
which you could try in your html directly. But, it has the consequence of having the blue
points hide some of the red ones which is probably worse. I think I'll have to leave this as-is
and hope it gets fixed upstream--there are several issues in plotly related to this, it seems to happen after >100K points and you have > 200K.

**Comment by brentp** [comment]
this should be fixed in latest release. if not, please re-open.
