### ISSUE TITLE
Feature Request: Support gVCF

### ISSUE THREAD

**Issue by holtjma** [brentp/somalier#27]
I've been able to use somalier without issue on Dragen VCF files, but I've encountered a nondescript error when trying on the Dragen gVCF file for the same sample.  Here's the message I'm getting:
```
[XXX@XXX ~]$ somalier extract -s sites.hg38.vcf.gz -f hg38.fa -d ~ [MASKED].hard-filtered.gvcf.gz
somalier version: 0.2.3
SIGABRT: Abnormal termination.
```
Not sure if this is a bug or a feature request.

**Comment by brentp** [comment]
I don't suppose you'd be able to share an example gvcf?
Meanwhile, I'll have a look as this is not the first time this has been requested and it seems a sensible input to somalier.

**Comment by brentp** [comment]
I am surprised that works. It's probably treating any reference call block as unknown. I am working on this now, so next release will have proper gvcf support.

**Comment by brentp** [comment]
hi, I have added this for the next release. if you have a chance, would be great if you could try it out. I get nearly identical results (<1% difference) between somalier from cram and somalier from GVCF.

Here is the updated binary:
[somalier.gz](https://github.com/brentp/somalier/files/3744768/somalier.gz)

thanks for bringing this up. I think it's a nice addition for somalier. I'll do more testing on my end as well, before next release.

**Comment by holtjma** [comment]
Below is the output I got from running it.  I got that same error for the original gVCF and the soft-linked "VCF".
```
somalier version: 0.2.4
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by brentp** [comment]
oh shoot. just made the release. can you run with this debug binary and let me know the output (along with the full command-line that you are running?)

[somalier_debug.gz](https://github.com/brentp/somalier/files/3752478/somalier_debug.gz)

thanks in advance.

**Comment by holtjma** [comment]
Yep, not a problem (obviously masked out some paths & such):
```
[XXX@XXX somalier-0.2.4]$ somalier_debug extract -s [MASK]/somalier-0.2.3/sites_files/sites.hg38.vcf.gz -f hg38.fa -d ~/interrupt [MASK].gvcf.gz
somalier version: 0.2.4
Traceback (most recent call last)
/home/brentp/src/somalier/src/somalier.nim(212) somalier
/home/brentp/src/somalier/src/somalier.nim(198) main
/home/brentp/src/somalier/src/somalier.nim(157) extract_main
/home/brentp/src/somalier/src/somalier.nim(61) get_ref_alt_counts
/home/brentp/src/somalier/src/somalier.nim(31) looks_like_gvcf_variant
/root/.nimble/pkgs/hts-#head/hts/vcf.nim(738) ALT
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by brentp** [comment]
ok. you must have some variants with an empty alt field? can you share the content of a single variant without an alt?

**Comment by holtjma** [comment]
just sent you an email with an example gVCF, hopefully that will help

**Comment by brentp** [comment]
I am able to run that gvcf with the changes added since last release. if you would try out this binary on a few samples, that would be a great help (in addition to the gvcf you already provided).
thanks very much for following up!
[somalier.gz](https://github.com/brentp/somalier/files/3756724/somalier.gz)

**Comment by holtjma** [comment]
Seems like that's working and generally finding more sites (~17k vs. ~10k) which I'm guessing should be expected.  I'm guessing this will be rolled into 0.2.5 when it's released?

**Comment by brentp** [comment]
yes, what I sent will be next release. i'll release this week. waiting to see if any new edge-cases like this one shake out since 0.2.4

**Comment by brentp** [comment]
this is out here: https://github.com/brentp/somalier/releases/tag/v0.2.5

thanks again.
