### ISSUE TITLE
Distinguish between bam files having the same bam sample ID

### ISSUE THREAD

**Issue by chenwenan** [brentp/somalier#43]
Hi, 

Thanks for developing this tool, which is very fast and easy to use.
I am trying to do WES WGS concordance check. One problem is that they may have the same bam sample ID in both the WES and WGS bam files. Could you add a feature to modify the bam sample ID in the extracted binary file? e.g., adding a prefix or suffix? I tried to change the file name but that does not seem to help when I run relate. 

Thanks

**Comment by brentp** [comment]
there's a pull request at #41 that addresses this. I'll get it merged and ready for next release. 
the limitation of that is that the sample ids will be different and won't match what you have in the pedigree file so duplicate samples "prefix-$sample" and $sample will have "expected_relatedness" from the pedigree file of 0.0 (so unrelated).

**Comment by chenwenan** [comment]
Great. Thank you.

**Comment by brentp** [comment]
this is out in latest release.
