### ISSUE TITLE
Limit number of threads used

### ISSUE THREAD

**Issue by fgvieira** [brentp/somalier#45]
Dear all,

is it possible to limit the number of threads `somalier`uses?
Right now it seems to use all available cpus.

thanks,

**Comment by brentp** [comment]
hi, do you mean `somalier ancestry`?

**Comment by fgvieira** [comment]
Yes, I've only noticed it on `somalier ancestry`, but was not sure if there was a general option that also affected other analyses.

**Comment by brentp** [comment]
ok. should only be in `ancestry`. I will have a look. Next release might be a few weeks off.

**Comment by brentp** [comment]
hi, you can do this now with `export OMP_NUM_THREADS=8 somalier ancestry ...`. I'll document this or make it a parameter for next release.

**Comment by HagemeijerRug** [comment]
Hi,
I know this is an old issue, but I just saw `somalier relate` also uses many cores. I haven't test the solution above yet, but just wanted to note it also happens in the `relate` sub-command.
