### ISSUE TITLE
Crash with 0.2.9

### ISSUE THREAD

**Issue by holtjma** [brentp/somalier#46]
Hello,

I was upgrading to 0.2.9 and I'm getting a crash now for some reason.  I have a parameterized snakemake command that looks like this:

```
{params.somalier} extract \
            -s {params.sites} \
            -f {params.ref} \
            -d {params.som_dir} \
            {input.vcf}
```

The only change I made was in the somalier executable path from the 0.2.5 binary to the 0.2.9 binary.  Weirdly, the 0.2.9 binary seems to work on some other VCF files I have generated from a different pipeline, but not on these which were historically working in 0.2.5.  Thoughts on debugging or additional details needed?

**Comment by brentp** [comment]
Hi Matt, thanks for reporting. Would you try this (debug) binary and let me know the error it reports?
[somalier_debug.gz](https://github.com/brentp/somalier/files/4433696/somalier_debug.gz)

**Comment by holtjma** [comment]
Can do:
```
somalier version: 0.2.9
/home/brentp/src/somalier/src/somalier.nim(274) somalier
/home/brentp/src/somalier/src/somalier.nim(261) main
/home/brentp/src/somalier/src/somalier.nim(217) extract_main
/home/brentp/src/somalier/src/somalier.nim(101) get_ref_alt_counts
/home/brentp/src/somalier/src/somalier.nim(40) get_variant
/nim/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```

**Comment by brentp** [comment]
ok. so this happens when `ALT` is empty (or "."). is this a gvcf?

**Comment by holtjma** [comment]
Yep, definitely gVCF generated by strelka-2.9.10; here's an example of the top lines:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SL409548
chr1	1	.	N	.	.	LowGQX	END=9994;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	.:.:0:0:0
chr1	9995	.	N	.	.	LowGQX;HighDPFRatio;LowDepth	END=9997;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	.:.:0:2:0
chr1	9998	.	N	.	.	LowGQX;HighDPFRatio;LowDepth	END=9999;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	.:.:0:10:0
chr1	10000	.	N	.	.	LowGQX;HighDPFRatio;HighDepth;LowDepth	.	GT:GQX:DP:DPF:MIN_DP	.:.:2:12:2
chr1	10001	.	T	C	0	LowGQX	SNVHPOL=3;MQ=13	GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL	0/1:19:0:4:14:3,1:3,1:0,0:0.0:LowGQX:22,0,37
chr1	10002	.	A	.	.	HighDPFRatio;HighDepth	END=10006;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	0/0:15:9:17:6
chr1	10007	.	T	.	.	HighDPFRatio;HighDepth	END=10020;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	0/0:39:23:26:14
```

**Comment by brentp** [comment]
ok. thanks very much for following up. here's another debug binary that should work. if you can verify, i'll get a test for this and a new release this week.
[somalier_debug2.gz](https://github.com/brentp/somalier/files/4434104/somalier_debug2.gz)

**Comment by holtjma** [comment]
That probably did it, identical command line outputs between 0.2.5 and 0.2.9_debug:
```
somalier version: 0.2.5
[somalier] found 13965 sites
```
```
somalier version: 0.2.9
[somalier] found 13965 sites
```

**Comment by brentp** [comment]
excellent. thanks again.

**Comment by brentp** [comment]
I just pushed the fix and test for this regression. I am planning to have the release out early next week.
