### ISSUE TITLE
relatedness = -nan and no HETs found

### ISSUE THREAD

**Issue by lconde-ucl** [brentp/somalier#5]
Hi,
I have some WGS, RNAseq and targeted RNAseq normal (no tumour) samples and I wanted to run somalier on them to find out if any of them are from the same individual (i.e., if for example I have WGS and RNAseq data from the same sample).

I had no problems running somalier, but the results are very confusing because somalier does not find any HETs in the data and the relatedness metric that I get is '-nan' for all the pairs of samples. This is the first few lines of the resulting somaliers.pairs.tsv file:

_#sample_a	sample_b	relatedness	hom_concordance	hets_a	hets_b	shared_hets	hom_alts_a	hom_alts_b	shared_hom_alts	ibs0	ibs2	n
ERR2322353	ERR2322354	-nan	0.827	0	0	0	4208	3456	2858	0	2858	2858
ERR2322353	ERR2322355	-nan	0.795	0	0	0	4208	3811	3030	0	3030	3030
ERR2322353	ERR2322356	-nan	0.847	0	0	0	4208	4875	3563	0	3563	3563
ERR2322353	ERR2322357	-nan	0.811	0	0	0	4208	3555	2884	0	2884	2884
ERR2322353	ERR2322358	-nan	0.805	0	0	0	4208	3710	2987	0	2987	2987_

I had tried to match these samples previously just by calling variants on all of them and checking the genotypes. While doing this, I was able to call both HOMs and REFs in all the samples (I'm using the HaplotypeCaller from GATK). So I was wondering if you could please let me know what the problem might be? I'm using the sites.vcf file provided by somalier.

Many thanks

**Comment by brentp** [comment]
could you share chromosome 1 of 2 of the bams?

**Comment by brentp** [comment]
emailing a link to dropbox or somehwere would be great.

**Comment by lconde-ucl** [comment]
Brilliant. I've uploaded chr1 of two BAMs, as well as the sites.vcf file that I used (it's the same one you provide but I added 'chr' to the chromosome names to match my BAMs and reference fasta)

https://www.dropbox.com/sh/1u7ev9190ib9bxu/AAB8AhZcRrMzoJOzVV9zbS7Ta?dl=0

**Comment by brentp** [comment]
looks like you lower-cased the REF and ALT columns too. Can you try with those upper-cased and let me know if the problem persists? Meanwhile, I am looking into why only the het stuff is empty for your example. Thanks very much for providing the data.

**Comment by lconde-ucl** [comment]
Hi, yes I had to lowercase the alleles too because my reference fasta is soft-masked, and somalier would throw a "mistmatch" error on these bases even if they are identical (i.e., somalier would crash with error: "_reference base from sites file:**G** does not match that from reference: **g**_"). So I  lower-cases all the sites as well as the fasta.
I will try to upper-case everything and see if that makes any difference.
Many thanks!

**Comment by brentp** [comment]
ok. I'll update the check to upper-case the allele pulled from fasta. Meanwhile, you might have to wait for next release or upper-case your entire fasta file.

**Comment by brentp** [comment]
Here is a new binary you can try. It will still require the VCF to be upper-cased, but it will not error if the fasta is lower-cased.
[somalier.gz](https://github.com/brentp/somalier/files/2813110/somalier.gz)

Please let me know if this works for you.

**Comment by lconde-ucl** [comment]
Thanks I will try it

**Comment by lconde-ucl** [comment]
Thanks, the new version is running without problems using the original sites.VCF (with 'chr's) and the original soft-masked FASTA. I will let you know if, when it finishes, I still find the issue with the lack of HETs and -nan relatedness.

**Comment by lconde-ucl** [comment]
Just to update you, the new version of somalier now worked well, at least the result files are now outputting HETs and relatedness metrics. The samples that should appear as related are not shown as related though, but that's what I got too with the other methods I tried, so it might be that indeed my samples were were all swapped :/

![screenshot 2019-01-30 at 16 39 29](https://user-images.githubusercontent.com/13676946/51997179-27abf100-24ae-11e9-8605-1a913bb45c8c.png)

**Comment by brentp** [comment]
thanks for updating. can you show this plot for IBS0 vs IBS2? And/or share the html via email? I should probably set the minimum relatedness value to -1 so there is better resolution as anything < 0 is unrelated.

**Comment by lconde-ucl** [comment]
Sure, I'll send the html by email, attaching here the plot

![screenshot 2019-01-30 at 16 50 04](https://user-images.githubusercontent.com/13676946/51997712-27f8bc00-24af-11e9-8ae7-011e84c3841d.png)

**Comment by lconde-ucl** [comment]
Html attached,
thanks for looking into this,
Best
Lucia



On 30 Jan 2019, at 16:48, Brent Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks for updating. can you show this plot for IBS0 vs IBS2? And/or share the html via email? I should probably set the minimum relatedness value to -1 so there is better resolution as anything < 0 is unrelated.

**Comment by brentp** [comment]
I am closing this as resolved. please re-open if you have further problems.
