### ISSUE TITLE
Basic IBSX question

### ISSUE THREAD

**Issue by holtjma** [brentp/somalier#51]
With somalier, we get the ibs0, ibs2, and n outputs in the *.pairs.tsv file.  This is likely a dumb question, but is this a correct inference from that info?
```
ibs1 = n - ibs0 - ibs2
```
I'm assuming that "n" is the total number of variants that overlap between the samples (i.e. non-shared are filtered out) and is basically counting the total number of variants used by somalier at any point in the process.  However, I couldn't find a description of each field in that file, so I wasn't sure if some other filtering took place that might make that inference incorrect.

**Comment by brentp** [comment]
Hi Matt, I think that's right, though I'm not sure of the precise definition of IBS1.
You can see the exact calculations in a very terse and (IMO) readable syntax here:
https://github.com/brentp/somalier/blob/master/src/somalierpkg/bitset.nim#L25-L31

**Comment by holtjma** [comment]
My assumption was IBS1 = one shared allele and one different allele as defined here (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3178600/).  I think given all the normal diploid assumptions and eye-balling that code segment, those assumptions would hold here as well.  Thanks for help clearing that up!

**Comment by brentp** [comment]
what do you use IBS1 for? if it's generally useful, i could add it to the plots.

**Comment by holtjma** [comment]
Nothing in particular, I was mostly checking my understanding of the IBSX and N values matched somalier.  Someone was asking me about a sample comparison, and I didn't directly have IBS1 to quantify.

**Comment by brentp** [comment]
ok. next release will scale IBS0 and IBS2 by n (#49) in the html plots. that seems to do a good job and sort of implicitly includes IBS1
