### ISSUE TITLE
Illegals storage access. (Attempt to read from nil)

### ISSUE THREAD

**Issue by vdejager** [brentp/somalier#53]
Hi Brent, 

I'm trying to compare two VCFs (hg19) for relatedness and stumbled on your tool.

somalier extract -d extracted/ --sites /home/victor/commondata/sites.hg19.vcf.gz -f /home/victor/commondata/human_g1k_v37_decoy.fasta 071181/071181_xAtlas.recode.sorted.vcf.gz
somalier version: 0.2.10
[W::bcf_hdr_check_sanity] PL should be declared as Number=G
[somalier] FORMAT field 'AD' not found for depth information. using genotype only
[somalier] found 10531 sites
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

any ideas how to resolve this? its probably a file that cannot be accessed similar to one ticked reported for slivar

**Comment by vdejager** [comment]
Hi Brent, the problem seems to be in the VCF file. If I run somalier with GATK3 VCF files it works perfectly. the xAtlas VCF file shows the above issue (tested with a variety of xAtlas files and GATK3 & 4 files. ).

**Comment by brentp** [comment]
Hi, can you share the input VCF file?

**Comment by vdejager** [comment]
I've send the link through your gmail account

**Comment by brentp** [comment]
Got it. Thanks for sending.
Your sample name is a long path, e.g. `/path/to/SNVCalling_20190403_xatlas/071180`. somalier tries to use that as part of a file to open (assuming it would be something like `sample_0711801`). I'll try to give a better error message for this, but even then you'll have to change your sample name to something that's not path-like.

**Comment by vdejager** [comment]
ah OK  I see, i'll rename the samples and try again

**Comment by brentp** [comment]
I am making a change so you'll see:
```
Error: unhandled exception: somalier: error opening file: extracted///path/to/xatlas/071180.somalier [IOError]
```
which will at least give a little more insight into what is going on.
