### ISSUE TITLE
ancestry output error 

### ISSUE THREAD

**Issue by olenamarchenko1234** [brentp/somalier#66]
I am getting the following exception when running somalier on sites from 10K genomes dataset. Error: unhandled exception: Broadcasting error: non-singleton dimensions must be the same in both tensors. Tensors' shapes were:[2504, 0] and [] [ValueError]

Any suggestions on how to debug this?

Thank you!

**Comment by brentp** [comment]
Can you show how you ran the tool?
You need to do, e.g.:
```
somalier ancestry [$args] 1kg/*.somalier ++ your-cohort/*.somalier
```
from this message, it looks like you only specified the thousand genomes samples and didn't give any cohort samples.

**Comment by olenamarchenko1234** [comment]
sites are extracted by chromosome. This is the command line with glob:
nohup time ./somalier ancestry --labels ancestry-labels-1kg.tsv 1kg-somalier/*.somalier extractedSSC_chr?/*.somalier extractedSSC_chr??/*.somalier > log_ancestry1112.out 2>&1

**Comment by brentp** [comment]
somalier won't work as intended if you extract sites by chromosome.

you also need to specify the background samples and the cohort samples separated by '++' as I indicated above.

**Comment by olenamarchenko1234** [comment]
Thank you. Any limitations on sample files/cohort size for somalier?

**Comment by brentp** [comment]
you should be able to do 10's of thousands. might get slow after 100K samples, but even for that size, the ancestry prediction should be fine.

**Comment by olenamarchenko1234** [comment]
Thanks!
