### ISSUE TITLE
Large number of n_unknown

### ISSUE THREAD

**Issue by mflevine** [brentp/somalier#7]
Hi Brent,

I ran somalier on ~500 targeted sequencing samples with average coverage of around 600X and ~1000 sites. I noticed that most samples are showing n_unknown of around 600 and as such most pairs only have about 250 sites in common used for comparison.

Any idea why so many sites are not able to be classified?

**Comment by brentp** [comment]
hmm, not sure. somalier does require that at least 40% of samples.
If you can share the `.pairs.tsv` and `.samples.tsv` files and/or the html, I can have a look.

**Comment by brentp** [comment]
oh. I think I see the problem. I count `nref`, `nalt`, `nother`. and then I have: ` if c.nother > 1'u32: return -1`
I should instead make that a fraction because for very deep coverage, it's likely you'll have some non-ref, non-alt alleles.

**Comment by brentp** [comment]
if you want to try it out, you can just change the > 1 here: https://github.com/brentp/somalier/blob/master/src/somalier.nim#L42
to e.g. > 20. Meanwhile, I'll commit a fix that checks this as a ratio rather than a fixed number.

**Comment by brentp** [comment]
or just pull as I made a quick change that should address this.

**Comment by mflevine** [comment]
Thanks! Ill try the fix and report back.

**Comment by mflevine** [comment]
Ok much better! Only seeing about 60 unknown for each sample and almost all are used in the pairs. Thanks!

**Comment by brentp** [comment]
excellent! thanks for reporting. let me know if you have any questions/bugs/features. Trying to round out the functionality.
