### ISSUE TITLE
Checking concordance between RNA and DNA samples

### ISSUE THREAD

**Issue by boyangzhao** [brentp/somalier#79]
Hi, I'm testing to use somalier for checking for sample swaps, to make sure all normal exome, tumor exome, and RNA-seq samples are from the same individual. While it's quite clear that with normal-tumor pair, looking at the hom_concordance indicate this (I see values close to 1s for same individual, and 0s for sample swaps), I'm wondering how to interpret comparisons between DNA and RNA samples. 

Your paper text mentioned this, but not quite clear how to extract this based on the data. I see hom_concordance has values ~0.5 for DNA-RNA pair from the same individual. Should we expect only that if the concordance is in the 0s that the samples (dna vs dna, or dna vs rna) are from likely different individuals?

**Comment by brentp** [comment]
Hi, are you looking at the HTML output? usually the related (in your case self-self) sample-pairs will cluster together, completely away from the unrelated sample pairs and this will give you an idea of what cutoffs you could use to separate them.

Are you using the RNA sites file?

**Comment by boyangzhao** [comment]
I was using a much earlier version (v0.1.5) where it was a direct call to `somalier`. And giving it a list of normal.bam, tumor.bam, and rna.bam. I presume this didn't work as it was using the dna sites (and rna sites were not included).

Should I run using the latest version, and run `somalier extract` first on a per sample basis: for dna examples give the dna vcf (e.g. sites.hg38.nochr.vcf.gz) and rna example give the rna vcf (e.g. sites.hg38.rna.vcf.gz)? And then run `somalier relate`?

**Comment by brentp** [comment]
Hi,
yes, run with latest version.
You must run `somalier extract` with the same sites for all samples and assays. I recommned to use `sites.hg38.rna.vcf.gz` that will work well for WGS too.
And yes, after extract for each sample, run `somalier relate ... *.somalier`

**Comment by boyangzhao** [comment]
Thank you! I got it to work!
