### ISSUE TITLE
somalier ancestry : Argument list too long

### ISSUE THREAD

**Issue by nrosewick** [brentp/somalier#81]
Related to https://github.com/brentp/somalier/issues/37 

I tried somalier ancestry on ~50k samples but I got a "Argument list too long" error. Any idea how to fix it ? or maybe provide a txt file with list of somalier files in input ? 

Thank you
N.

**Comment by brentp** [comment]
Hi, you can use a glob (and quote it to prevent it from being expanded by your shell), something like:

```
somalier ancestry ... '/path/to/my-samples/*/*.somalier' ++ '/path/to/1kg/*.somalier'
```

**Comment by nrosewick** [comment]
Ok great. It's working perfectly :-) 

Thanks Brent !

**Comment by brentp** [comment]
Great. Thanks for following up. I should update the docs, but be careful with the somalier ancestry results. I'd call it "still in development". It doesn't do well for unknown ancestries. It will confidently predict an ancestry even if it should be uknown or low confidence, but should work quite well for ancestries matching those in your training set (or 1kg if that's what you're using).
