### ISSUE TITLE
HTML report

### ISSUE THREAD

**Issue by Danisov** [brentp/somalier#83]
Hi,

I ran both 10 trio, one duo and 11 unrelated samples using bam file.

Two slightly strange things I found in the html report.
1: for the duo it is well placed among parent-child but the point color corresponds to the color as unrelated samples.
2: A female sample, it is well palced among the female samples but the point coloring (gray) is different compared to the others female.

Do you have an idea ??

**Comment by brentp** [comment]
1: this should not be the case, but you can try adding a fake dad to the kid. e.g. "fakedad". and then add a sample line for the fakedad. e.g.: `$fam_id fakedad -9 -9 1 -9`. Can you show the lines for the 2 samples?

2: likewise, can you show the line in the pedigree file for this sample?

**Comment by Danisov** [comment]
Hi @brentp 
Please find the first line corresponds to the duo (samplaA and sampleB). The second corresponds to the sample long with original sex pedigree unknown (sample1) 
```
#family_id | sample_id | paternal_id | maternal_id | sex | original_pedigree_sex | gt_depth_mean | gt_depth_sd | depth_mean | depth_sd | ab_mean | ab_std | n_hom_ref | n_het | n_hom_alt | n_unknown | p_middling_ab | X_depth_mean | X_n | X_hom_ref | X_het | X_hom_alt | Y_depth_mean | Y_n
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
sampleA | sampleB |   |   | 1 | male | 39.6 | 7.6 | 39.6 | 7.6 | 0.53 | 0.39 | 4594 | 6869 | 5613 | 308 | 0.009 | 19.78 | 356 | 181 | 0 | 175 | 20.33 | 15
sample1 | sample1 |   |   |   | unknown | 35.6 | 7.3 | 35.6 | 7.4 | 0.53 | 0.39 | 4060 | 6668 | 5060 | 1596 | 0.071 | 35.41 | 341 | 105 | 138 | 98 | 0.00 | 0
```

**Comment by brentp** [comment]
This line: `sampleA	sampleB			1	male` is a single sample. Where's the other sample in that family? It will need to have the same family id (`sampleA`) for somalier to match it.

This line: `sample1	sample1				unknown` shows that there is no sex specified in the column of the pedigree file. 

So you just need to update the pedigree file that you send to somalier to include the sex and the include some value for sampleA.

**Comment by Danisov** [comment]
Hi @brentp sorry for the delay of my answe
I  used pedigree file obtained by somalier. For a reason of validation of  the manipulations within our laboratory, was asked to determine the sex  and the relatedness within these samples without having an idea on their sex  and real relatedness that's why I used the pedigree file obtained by  somalier.

The question I ask myself: is that for the sex and the  relatedness was well determined in the pedigree file obtained by  somalier with the exception of the samples that I  had mentioned

**Comment by brentp** [comment]
Hi, I'm not able to understand your response.
If you can respond to my previous message point-by-point, perhaps I can help.
Or if I miss a question in your latest, I will attempt to help if you can clarify.
