### ISSUE TITLE
n in relatedness result

### ISSUE THREAD

**Issue by wac** [brentp/somalier#86]
Hello!  Just wanted to confirm the "n" in the relatedness result (the "pairs.tsv" output file) - I'm guessing that it is perhaps the number of sites shared between sample_a and sample_b?

I'm also guessing the x_ibs0 and x_ibs2 are the expected ibs0 and ibs2 based on the provided pedigree?

Thank you!

**Comment by brentp** [comment]
Hi, `n` is the number of sites where both samples have a known genotype.

x_ibs0 and x_ibs2 are like ibs0 and ibs2, but for the x-chromosome only.
