### ISSUE TITLE
Bioconda recipe for somalier

### ISSUE THREAD

**Issue by tamuanand** [brentp/somalier#92]
Hi 

Thanks for the great tool. Is it possible to have this made available via Bioconda

Thanks in advance

**Comment by brentp** [comment]
It is possible, but I haven't written a recipe. You could write one using the slivar or mosdepth recipe as a guide.

**Comment by jfy133** [comment]
I copied mosdepth and borrowed a tiny bit from sl8ver and it seems to work!

https://github.com/bioconda/bioconda-recipes/pull/36877

Only limitation is that following the slivar, recipe doesn't support OSX but 🤷‍♀️. At least this way there will be also biocontainers available :)

**Comment by brentp** [comment]
thanks for doing this James!
