### ISSUE TITLE
No output - docker

### ISSUE THREAD

**Issue by krukanna** [brentp/somalier#94]
Hi, I'm using docker image, docker command `extract` works fine and I got outputs in right directory, but docker `relate` gives such information:
```
somalier version: 0.2.15
[somalier] starting read of 102 samples
[somalier] time to read files and get per-sample stats for 102 samples: 0.07
[somalier] time to get expected relatedness from pedigree graph: 0.00
couldn't open output file
```
I cannot find any output. I need to use it in nextflow.
Thanks in advance.

**Comment by krukanna** [comment]
I run this with command:

`docker run --user $(id -u):$(id -g) -v /home/bioinf/:/data/ brentp/somalier:latest somalier relate --ped data/shared/RodzWES/fam_file.fam /data/Relatedness/docker/extract/*.somalier `

**Comment by brentp** [comment]
you'll probably need to add `--output-prefix /data/rodzwes`

**Comment by krukanna** [comment]
thanks a lot
